#Available Languages: en, de
Language: en
#Enable default permissions for everyone
defaultpermissions: true
#Set a home limit, set to 0 if no limit
homelimit: 0
#Add a world where a player shouldn't be allowed to set a home
blockedworlds: 
- Example1
- Example2